# Infrastructure Team Organization Definitions
# This file contains organization definitions managed by the infrastructure team

schema_version: "1.0"

organizations:
  infrastructure:
    description: "Infrastructure and base images managed by infrastructure team"
    images:
      docker.io/library/ubuntu:
        description: "Ubuntu base images"
        type: "container"
        versions:
          pattern: "^22\\.04.*$"
        tags:
          - "latest"
          - "22.04"

      docker.io/library/alpine:
        description: "Alpine base images"
        type: "container"
        versions:
          pattern: "^3\\.[0-9]+\\.[0-9]+$"
        tags:
          - "latest"
          - "3.19"
          - "3.20"

  helm-charts:
    description: "OCI-based Helm charts"
    images:
      docker.io/bitnamicharts/postgresql:
        description: "PostgreSQL Helm chart as OCI artifact"
        type: "oci-helm"
        versions:
          pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
        tags:
          - "latest"

      docker.io/bitnamicharts/redis:
        description: "Redis Helm chart as OCI artifact"
        type: "oci-helm"
        versions:
          pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
        tags:
          - "latest"