# Organization Definitions for Image Import Pipeline
# This file contains only organization and repository definitions
# Global settings (registry, policies) are defined in the main application repository

schema_version: "1.0"

# Organization definitions - these can be managed by different teams
organizations:
  # Ubuntu base images
  ubuntu:
    description: "Ubuntu base images"
    images:
      docker.io/library/ubuntu:
        description: "Official Ubuntu images"
        type: "container"
        versions:
          pattern: "^22\\.04.*$"
        tags:
          - "latest"
          - "22.04"

  # Redis database images
  redis:
    description: "Redis database images"
    images:
      docker.io/library/redis:
        description: "Official Redis images"
        type: "container"
        versions:
          pattern: "^7\\.[0-9]+\\.[0-9]+$"
        tags:
          - "latest"
          - "alpine"

  # Test containers for development
  test-containers:
    description: "Test container images for development"
    images:
      docker.io/nginx:
        description: "Nginx test image"
        type: "container"
        versions:
          - "1.29.1-perl"
          - "1.29-bookworm-perl"
        tags:
          - "latest"

      docker.io/alpine::
        description: "Alpine test image"
        type: "container"
        versions:
          - "3.19.8"
          - "3.20.7"
        tags:
          - "latest"

  # OCI-based Helm charts
  test-helm-charts:
    description: "Test OCI-based Helm charts"
    images:
      docker.io/bitnamicharts/postgresql:
        description: "PostgreSQL Helm chart as OCI artifact"
        type: "oci-helm"
        versions:
          - "12.1.0"
          - "13.1.0"

      docker.io/bitnamicharts/redis:
        description: "Redis Helm chart as OCI artifact"
        type: "oci-helm"
        source:
          registry: "docker.io"
          repository: "bitnamicharts/redis"
        versions:
          - "17.1.0"
          - "18.1.0"